In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('adult.csv')
df.head()

,age,workclass,fnlwgt,education,educational-num,marital-status,occupation,relationship,race,gender,capital-gain,capital-loss,hours-per-week,native-country,income
0,25,Private,226802,11th,7,Never-married,Machine-op-inspct,Own-child,Black,Male,0,0,40,United-States,<=50K
1,38,Private,89814,HS-grad,9,Married-civ-spouse,Farming-fishing,Husband,White,Male,0,0,50,United-States,<=50K
2,28,Local-gov,336951,Assoc-acdm,12,Married-civ-spouse,Protective-serv,Husband,White,Male,0,0,40,United-States,>50K
3,44,Private,160323,Some-college,10,Married-civ-spouse,Machine-op-inspct,Husband,Black,Male,7688,0,40,United-States,>50K
4,18,?,103497,Some-college,10,Never-married,?,Own-child,White,Female,0,0,30,United-States,<=50K

In [3]:
df = df[['age','income']]
df.head()

   age income
0   25  <=50K
1   38  <=50K
2   28   >50K
3   44   >50K
4   18  <=50K

In [4]:
df['income'] = df['income'].astype(str).str.strip()

In [5]:
grouped = df.groupby('income')['age']

In [6]:
summary = grouped.agg(['mean','median','min','max','std'])
summary

             mean  median  min  max        std
income
<=50K   36.872184    34.0   17   90  14.104118
>50K    44.275178    43.0   19   90  10.558983

In [7]:
age_list = grouped.apply(list)
age_list

income
<=50K    [25, 38, 18, 34, 29, 24, 55, 36, 26, 58, 20, 4...
>50K     [28, 44, 63, 65, 48, 43, 40, 34, 45, 46, 36, 6...
Name: age, dtype: object

In [9]:
iris = pd.read_csv('Iris.csv')
iris.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [10]:
iris['Species'].unique()

<StringArray>
['Iris-setosa', 'Iris-versicolor', 'Iris-virginica']
Length: 3, dtype: str

In [11]:
setosa = iris[iris['Species'] == 'Iris-setosa']

In [12]:
versicolor = iris[iris['Species'] == 'Iris-versicolor']

In [13]:
virginica = iris[iris['Species'] == 'Iris-virginica']

In [14]:
setosa.describe()

             Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count  50.00000       50.00000     50.000000      50.000000      50.00000
mean   25.50000        5.00600      3.418000       1.464000       0.24400
std    14.57738        0.35249      0.381024       0.173511       0.10721
min     1.00000        4.30000      2.300000       1.000000       0.10000
25%    13.25000        4.80000      3.125000       1.400000       0.20000
50%    25.50000        5.00000      3.400000       1.500000       0.20000
75%    37.75000        5.20000      3.675000       1.575000       0.30000
max    50.00000        5.80000      4.400000       1.900000       0.60000

In [15]:
versicolor.describe()

              Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count   50.00000      50.000000     50.000000      50.000000     50.000000
mean    75.50000       5.936000      2.770000       4.260000      1.326000
std     14.57738       0.516171      0.313798       0.469911      0.197753
min     51.00000       4.900000      2.000000       3.000000      1.000000
25%     63.25000       5.600000      2.525000       4.000000      1.200000
50%     75.50000       5.900000      2.800000       4.350000      1.300000
75%     87.75000       6.300000      3.000000       4.600000      1.500000
max    100.00000       7.000000      3.400000       5.100000      1.800000

In [16]:
virginica.describe()

              Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count   50.00000       50.00000     50.000000      50.000000      50.00000
mean   125.50000        6.58800      2.974000       5.552000       2.02600
std     14.57738        0.63588      0.322497       0.551895       0.27465
min    101.00000        4.90000      2.200000       4.500000       1.40000
25%    113.25000        6.22500      2.800000       5.100000       1.80000
50%    125.50000        6.50000      3.000000       5.550000       2.00000
75%    137.75000        6.90000      3.175000       5.875000       2.30000
max    150.00000        7.90000      3.800000       6.900000       2.50000

In [25]:
virginica_num = virginica.select_dtypes(include='number')

In [26]:
virginica_num.quantile([0.25, 0.5, 0.75])

          Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
0.25  113.25          6.225         2.800          5.100           1.8
0.50  125.50          6.500         3.000          5.550           2.0
0.75  137.75          6.900         3.175          5.875           2.3

In [27]:
virginica_num.mean()

Id               125.500
SepalLengthCm      6.588
SepalWidthCm       2.974
PetalLengthCm      5.552
PetalWidthCm       2.026
dtype: float64

In [28]:
virginica_num.std()

Id               14.577380
SepalLengthCm     0.635880
SepalWidthCm      0.322497
PetalLengthCm     0.551895
PetalWidthCm      0.274650
dtype: float64

In [29]:
setosa_num = setosa.select_dtypes(include='number')

In [30]:
setosa_num.quantile([0.25, 0.5, 0.75])

         Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
0.25  13.25            4.8         3.125          1.400           0.2
0.50  25.50            5.0         3.400          1.500           0.2
0.75  37.75            5.2         3.675          1.575           0.3

In [31]:
setosa_num.mean()

Id               25.500
SepalLengthCm     5.006
SepalWidthCm      3.418
PetalLengthCm     1.464
PetalWidthCm      0.244
dtype: float64

In [32]:
setosa_num.std()

Id               14.577380
SepalLengthCm     0.352490
SepalWidthCm      0.381024
PetalLengthCm     0.173511
PetalWidthCm      0.107210
dtype: float64

In [33]:
versicolor_num = versicolor.select_dtypes(include='number')

In [34]:
versicolor_num.quantile([0.25, 0.5, 0.75])

         Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
0.25  63.25            5.6         2.525           4.00           1.2
0.50  75.50            5.9         2.800           4.35           1.3
0.75  87.75            6.3         3.000           4.60           1.5

In [35]:
versicolor_num.mean()

Id               75.500
SepalLengthCm     5.936
SepalWidthCm      2.770
PetalLengthCm     4.260
PetalWidthCm      1.326
dtype: float64

In [36]:
versicolor_num.std()

Id               14.577380
SepalLengthCm     0.516171
SepalWidthCm      0.313798
PetalLengthCm     0.469911
PetalWidthCm      0.197753
dtype: float64

In [37]:
setosa.select_dtypes(include='number').describe()
versicolor.select_dtypes(include='number').describe()
virginica.select_dtypes(include='number').describe()

              Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count   50.00000       50.00000     50.000000      50.000000      50.00000
mean   125.50000        6.58800      2.974000       5.552000       2.02600
std     14.57738        0.63588      0.322497       0.551895       0.27465
min    101.00000        4.90000      2.200000       4.500000       1.40000
25%    113.25000        6.22500      2.800000       5.100000       1.80000
50%    125.50000        6.50000      3.000000       5.550000       2.00000
75%    137.75000        6.90000      3.175000       5.875000       2.30000
max    150.00000        7.90000      3.800000       6.900000       2.50000